name: Selenium workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    container:
      image: node:16

    services:
      selenium:
        image: selenium/standalone-chrome

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm install
      - run: apt install chromium-chromedriver
      - run: npm install -g serve
      - run: npm install -g pm2
      - run: npm run build
      - run: pm2 serve dist 8080 --name=ReactApp
      - run: npm run test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: screenshots
          path: screenshots/